services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:${CONTAINER_PORT}"
    environment:
      VITE_API_URL: "${VITE_API_URL}"
    networks:
      - imgmesser-network

networks:
  imgmesser-network:
    external: true
    name: imgmesser-network
