services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1986:1986"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws
    depends_on:
      - db
    networks:
      - imgmesser-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      # Persist database data to a volume on the host machine
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imgmesser-network

networks:
  imgmesser-network:
    external: true
    name: imgmesser-network

volumes:
  postgres_data:
