name: imgmesser

services:
  app:
    image: rkooy/imgmesser-app:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot_webroot:/var/www/certbot:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro # Mount point for real certs
    profiles:
      - nginx
    depends_on:
      - certbot
    networks:
      - imgmesser-nw

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot_webroot:/var/www/certbot:rw
      - ./etc/letsencrypt:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - imgmesser-nw

  api:
    image: rkooy/imgmesser-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      imgmesser-nw:
        ipv4_address: 172.20.0.10

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      # Persist database data to a volume on the host machine
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imgmesser-nw

networks:
  imgmesser-nw:
    external: true
    name: imgmesser-nw

volumes:
  postgres_data:
