[package]
name = "s3"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
aws-config = "1.8.8"
aws-sdk-s3.workspace = true
bytes.workspace = true
dotenv.workspace = true
tracing.workspace = true
